name: 'Railway Deploy'
description: 'Simple Action to Deploy Railway App using Railway CLI'
inputs:
  service: # the specific service target
    description: 'The specific service target'
    required: true
  detach: # detatch option
    description: 'Detach option in the railway cli option'
    required: false
outputs:
  status: # status output
    description: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.service }}
    - ${{ inputs.detach }}
